data:
  folder: model_hx/
  age_col: TrueAge
  train:
    train:
      csv: ./Train-df.csv
      trace: ./Train-np.npy
    valid:
      csv: ./Valid-df.csv
      trace: ./Valid-np.npy
  validation:
    test: 
      csv : ./Test-df.csv
      trace : ./Test-np.npy
    

setup:
  phase: train
  epochs: 100
  earlystop : 30
  batch_size: 512
  seed: 42
  sample_freq: 500
  seq_length: 5000 # size for all traces; 5000 for 10 sec 500Hz tracing
  num_workers : 28
  ec2: g4dn.metal

module:
  model:
    name: RNN15
    model_name: # fill this area
    data_parallel : True
    dropout_rate: 0.5
    net_filter_size: [64, 128, 196, 256, 320] # filter size in resnet layers 
    net_seq_length: [5000, 1000, 200, 40, 8] # number of samples per resnet layer
    kernel_size: 17 # kernel size in convolutional layers

  optim: 
    name: Adam
    lr: 0.001 # learning rate
    patience: 7 # maximum number epochs without reducing the lr
    min_lr: 0.0000001 # minimum lr
    lr_factor: 0.1 # reducing factor for the lr in a plateu 
    lr_scheduler: ReduceLROnPlateau

  loss: MSE
  age_range: 20 to 90 
  code_to_run: python train.py resnet
